### ISSUE TITLE
ansible-go fails to install go under some circumstances.

### ISSUE THREAD

**Issue by jonseymour** [jlund/ansible-go#22]
ansible-go is failing for me, apparently because of this ansible get_url [issue](https://github.com/ansible/ansible/issues/11579#issuecomment-121775819):

Namely, the vanilla ubuntu 14.04.4 host I wish to install go into has python 2.7.6 installed, which doesn't handle SNI. 

The suggested workaround is to not validate certificates (which seems sloppy) or to use curl or wget as an alternative.

I was wondering how open you would be to a configuration option in your role that allowed the use of curl as an alternative?

Alternatively, can you suggest another way I can structure my ansible playbook so that I can avoid this issue and still use your role?

Here is the vvv output from my attempt to install go 1.6.:

```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "checksum": "", "content": null, "delimiter": null, "dest": "/usr/local/src/go1.6.linux-amd64.tar.gz", "directory_mode": null, "follow": false, "force": false, "force_basic_auth": false, "group": null, "headers": null, "http_agent": "ansible-httpget", "mode": null, "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "sha256sum": "5470eac05d273c74ff8bac7bef5bad0b5abbd1c4052efbdbc8db45332e836b0b", "src": null, "timeout": 10, "url": "https://golang.org/dl/go1.6.linux-amd64.tar.gz", "url_password": null, "url_username": null, "use_proxy": true, "validate_certs": true}, "module_name": "get_url"}, "msg": "SSL Certificate does not belong to golang.org.  Make sure the url has a certificate that belongs to it or use validate_certs=False (insecure)"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=11   changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by jonseymour** [comment]
BTW: one workaround was to follow the redirect manually for the current version and adjust the playbook to refer to the final URL with a `go_download_location`.

`{ role: ansible-go, go_download_location: "https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz" }`

TBH: I haven't actually verified that an upgrade to python 2.7.9 addresses the issue - there may be a separate issue with get_url with regard to following https redirects. I will do some more digging tomorrow.

**Comment by jlund** [comment]
I fixed this like you suggested by specifying the new download location and removing the need for the redirect. Thanks for the report!
