### ISSUE TITLE
Meta says this module compatible with Ansible 1.3, but it isn't

### ISSUE THREAD

**Issue by judy2k** [jlund/ansible-go#24]
`get_url` only gained a checksum parameter in Ansible 2.0 [see here](file:///Users/mark/Library/Application%20Support/Dash/DocSets/Ansible/Ansible.docset/Contents/Resources/Documents/docs.ansible.com/ansible/get_url_module.html)

**Comment by jlund** [comment]
Thanks for the report!

**Comment by judy2k** [comment]
Thanks for fixing!
